### ISSUE TITLE
What is 'concurrency' in this context?

### ISSUE THREAD

**Issue by hachi** [chemoish/videojs-concurrency#2]
A quick search for 'javascript concurrency' is not helping me figure out what this plugin does.

Does Video.js not allow concurrent playback of two files on the same page?

Is concurrency a codename for some framework or system that I'm not finding with google?

Thanks

**Comment by mokiding** [comment]
@chemoish yea really ?!

**Comment by chemoish** [comment]
@hachi, sorry missed your message.

See below.

@m0k1, it sounds like github has great SEO.

This plugin originally was created for a specific video use case,,, many users sharing the same account playing DRM'd content.

e.g. Netflix prevents 3 concurrent streams from the same account.

Since then I have come to realize that this implementation is so application centric it doesn't make sense to generalize the implementation.

This repository can be used as an example of an implementation strategy. Hope that helps.
